export const promoCategories = [
  {
    ProductName: "Soft drink",
    image: require("../../assets/images/softDrink.jpeg"),
    Price: 20,
    DiscountPrice: 15,
    Rating: "4.5 of 5 stars",
    NumberofReviews: "200",
    ShortDescription: "sample discription",
    id: "0",
  },
  {
    ProductName: "Alcholic drink",
    image: require("../../assets/images/alcolicDirnk.jpeg"),
    Price: 20,
    DiscountPrice: 15,
    Rating: "4.5 of 5 stars",
    NumberofReviews: "200",
    ShortDescription: "sample discription",
    id: "1",
  },
  {
    ProductName: "Vegetable",
    image: require("../../assets/images/vegetable.jpeg"),
    Price: 20,
    DiscountPrice: 15,
    Rating: "4.5 of 5 stars",
    NumberofReviews: "200",
    ShortDescription: "sample discription",
    id: "2",
  },
  {
    ProductName: "Pcked food",
    image: require("../../assets/images/packedfood.jpeg"),
    Price: 20,
    DiscountPrice: 15,
    Rating: "4.5 of 5 stars",
    NumberofReviews: "200",
    ShortDescription: "sample discription",
    id: "3",
  },
  {
    ProductName: "cosmotics",
    image: require("../../assets/images/cosmotics.jpeg"),
    Price: 20,
    DiscountPrice: 15,
    Rating: "4.5 of 5 stars",
    NumberofReviews: "200",
    ShortDescription: "sample discription",
    id: "4",
  },
  {
    ProductName: "Fruit",
    image: require("../../assets/images/fruit.jpeg"),
    Price: 20,
    DiscountPrice: 15,
    Rating: "4.5 of 5 stars",
    NumberofReviews: "200",
    ShortDescription: "sample discription",
    id: "5",
  },
];

export const standard = [
  {
    ProductName: "Soft drink",
    image: require("../../assets/images/softDrink.jpeg"),
    Price: 20,
    DiscountPrice: 15,
    Rating: "4.5 of 5 stars",
    NumberofReviews: "200",
    ShortDescription: "sample discription",
    id: "0",
  },
  {
    ProductName: "Alcholic drink",
    image: require("../../assets/images/alcolicDirnk.jpeg"),
    Price: 20,
    DiscountPrice: 15,
    Rating: "4.5 of 5 stars",
    NumberofReviews: "200",
    ShortDescription: "sample discription",
    id: "1",
  },
  {
    ProductName: "Vegetable",
    image: require("../../assets/images/vegetable.jpeg"),
    Price: 20,
    DiscountPrice: 15,
    Rating: "4.5 of 5 stars",
    NumberofReviews: "200",
    ShortDescription: "sample discription",
    id: "2",
  },
  {
    ProductName: "Pcked food",
    image: require("../../assets/images/packedfood.jpeg"),
    Price: 20,
    DiscountPrice: 15,
    Rating: "4.5 of 5 stars",
    NumberofReviews: "200",
    ShortDescription: "sample discription",
    id: "3",
  },
  {
    ProductName: "cosmotics",
    image: require("../../assets/images/cosmotics.jpeg"),
    Price: 20,
    DiscountPrice: 15,
    Rating: "4.5 of 5 stars",
    NumberofReviews: "200",
    ShortDescription: "sample discription",
    id: "4",
  },
];
export const recomended = [
  {
    ProductName: "Soft drink",
    image: require("../../assets/images/softDrink.jpeg"),
    Price: 20,
    DiscountPrice: 15,
    Rating: "4.5 of 5 stars)",
    NumberofReviews: "200",
    ShortDescription: "sample discription",
    id: "0",
  },
  {
    ProductName: "Alcholic drink",
    image: require("../../assets/images/alcolicDirnk.jpeg"),
    Price: 20,
    DiscountPrice: 15,
    Rating: "4.5 of 5 stars",
    NumberofReviews: "200",
    ShortDescription: "sample discription",
    id: "1",
  },
  {
    ProductName: "Vegetable",
    image: require("../../assets/images/vegetable.jpeg"),
    Price: 20,
    DiscountPrice: 15,
    Rating: "4.5 of 5 stars",
    NumberofReviews: "200",
    ShortDescription: "sample discription",
    id: "2",
  },
  {
    ProductName: "Pcked food",
    image: require("../../assets/images/packedfood.jpeg"),
    Price: 20,
    DiscountPrice: 15,
    Rating: "4.5 of 5 stars",
    NumberofReviews: "200",
    ShortDescription: "sample discription",
    id: "3",
  },
  {
    ProductName: "cosmotics",
    image: require("../../assets/images/cosmotics.jpeg"),
    Price: 20,
    DiscountPrice: 15,
    Rating: "4.5 of 5 stars",
    NumberofReviews: "200",
    ShortDescription: "sample discription",
    id: "4",
  },
];

export const VegetableCategory = [
  {
    VegetableName: "Onions",
    image: require("../../assets/images/Onions.png"),
    Price: 20,
    DiscountPrice: 15,
    Rating: "4.5 of 5 stars)",
    NumberofReviews: "200",
    ShortDescription: "sample Onions",
    id: "0",
    catagory: "Vegetable",
    ingredients: "raw onion",
    nutritionalInformation: "calories: 40, protien: 1.1g, carbs: 9.3g",
    Amount: "1kg",
    PackageType: "Bag",
    SupplierName: "ona",
    Origin: "ethiopia",
  },
  {
    VegetableName: "cabbage",
    image: require("../../assets/images/Cabbage.jpeg"),
    Price: 20,
    DiscountPrice: 15,
    Rating: "4.5 of 5 stars)",
    NumberofReviews: "200",
    ShortDescription: "sample cabbage",
    id: "1",
    SupplierName: "caba",
    Origin: "ethiopia",
    ingredients: "cabbage",
    nutritionalInformation: "calories: 25, protien: 1.3g, carbs: 5.8g",
    Amount: "1kg",
    PackageType: "Bag",
    catagory: "Vegetable",
  },
  {
    VegetableName: "carot",
    image: require("../../assets/images/carot.jpeg"),
    Price: 20,
    DiscountPrice: 15,
    Rating: "4.5 of 5 stars)",
    NumberofReviews: "200",
    ShortDescription: "sample carot",
    id: "2",
    catagory: "Vegetable",
    ingredients: "carot",
    nutritionalInformation: "calories: 41, protien: 0.9g, carbs: 9.6g",
    Amount: "1kg",
    PackageType: "Bag",
    SupplierName: "caro",
    Origin: "ethiopia",
  },
  {
    VegetableName: "tomato",
    image: require("../../assets/images/tomato.jpeg"),
    Price: 20,
    DiscountPrice: 15,
    Rating: "4.5 of 5 stars)",
    NumberofReviews: "200",
    ShortDescription: "sample tomato",
    id: "3",
    catagory: "Vegetable",
    ingredients: "vegetable",
    nutritionalInformation: "calories: 18, protien: 0.9g, carbs: 3.9g",
    Amount: "1kg",
    PackageType: "Bag",
    SupplierName: "toma",
    Origin: "ethiopia",
  },
  {
    VegetableName: "potato",
    image: require("../../assets/images/Potatoes.png"),
    Price: 20,
    DiscountPrice: 15,
    Rating: "4.5 of 5 stars)",
    NumberofReviews: "200",
    ShortDescription: "sample potato",
    id: "5",
    catagory: "Vegetable",
    ingredients: "potato",
    nutritionalInformation: "calories: 77, protien: 2g, carbs: 17g",
    Amount: "1kg",
    PackageType: "Bag",
    SupplierName: "pota",
    Origin: "ethiopia",
  },
];

export const FruitCategiry = [
  {
    fruitName: "mango",
    image: require("../../assets/images/mango.png"),
    Price: 20,
    DiscountPrice: 15,
    Rating: "4.5 of 5 stars)",
    NumberofReviews: "200",
    ShortDescription: "sample mango",
    id: "0",
    catagory: "Fruit",
    ingredients: "mango",
    nutritionalInformation: "calories: 60, protien: 0.8g, carbs: 15g",
    Amount: "1kg",
    PackageType: "Bag",
    SupplierName: "mang",
    Origin: "ethiopia",
  },
  {
    fruitName: "orange",
    image: require("../../assets/images/orange.png"),
    Price: 20,
    DiscountPrice: 15,
    Rating: "4.5 of 5 stars)",
    NumberofReviews: "200",
    ShortDescription: "sample orange",
    id: "1",
    catagory: "Fruit",
    ingredients: "orange",
    nutritionalInformation: "calories: 43, protien: 1g, carbs: 9g",
    Amount: "1kg",
    PackageType: "Bag",
    SupplierName: "oran",
    Origin: "ethiopia",
  },
  {
    fruitName: "Lemon",
    image: require("../../assets/images/lemon.jpeg"),
    Price: 20,
    DiscountPrice: 15,
    Rating: "4.5 of 5 stars)",
    NumberofReviews: "200",
    ShortDescription: "sample Lemon",
    id: "2",
    catagory: "Fruit",
    ingredients: "lemon",
    nutritionalInformation: "calories: 29, protien: 1.1g, carbs: 9.3g",
    Amount: "1kg",
    PackageType: "Bag",
    SupplierName: "lemo",
    Origin: "ethiopia",
  },
  {
    fruitName: "papaya",
    image: require("../../assets/images/Papaya.png"),
    Price: 20,
    DiscountPrice: 15,
    Rating: "4.5 of 5 stars)",
    NumberofReviews: "200",
    ShortDescription: "sample papaya",
    id: "3",
    catagory: "Fruit",
    ingredients: "papaya",
    nutritionalInformation: "calories: 43, protien: 0.5g, carbs: 11g",
    Amount: "1kg",
    PackageType: "Bag",
    SupplierName: "papa",
    Origin: "ethiopia",
  },
  {
    fruitName: "Banana",
    image: require("../../assets/images/Banana.jpeg"),
    Price: 20,
    DiscountPrice: 15,
    Rating: "4.5 of 5 stars)",
    NumberofReviews: "200",
    ShortDescription: "sample Banana",
    id: "4",
    catagory: "Fruit",
    ingredients: "banana",
    nutritionalInformation: "calories: 89, protien: 1.1g, carbs: 23g",
    Amount: "1kg",
    PackageType: "Bag",
    SupplierName: "bana",
    Origin: "ethiopia",
  },
];

export const PackedFoodCategory = [
  {
    foodName: "Pasta",
    image: require("../../assets/images/pasta.png"),
    Price: 20,
    DiscountPrice: 15,
    Rating: "4.5 of 5 stars)",
    NumberofReviews: "200",
    ShortDescription: "sample pasta",
    id: "0",
    catagory: "PackedFood",
    ingredients: "pasta",
    nutritionalInformation: "calories: 131, protien: 5.5g, carbs: 25g",
    Amount: "500g",
    PackageType: "Bag",
    SupplierName: "past",
    Origin: "ethiopia",
  },
  {
    foodName: "Biscuit",
    image: require("../../assets/images/Biscuits.png"),
    Price: 20,
    DiscountPrice: 15,
    Rating: "4.5 of 5 stars)",
    NumberofReviews: "200",
    ShortDescription: "sample biscuit",
    id: "1",
    catagory: "PackedFood",
    ingredients: "suagr, flour, butter",
    nutritionalInformation: "calories: 131, protien: 5.5g, carbs: 25g",
    Amount: "500g",
    PackageType: "Bag",
    SupplierName: "bisc",
    Origin: "ethiopia",
  },
  {
    foodName: "Energy Bars",
    image: require("../../assets/images/EnergyBars.png"),
    Price: 20,
    DiscountPrice: 15,
    Rating: "4.5 of 5 stars)",
    NumberofReviews: "200",
    ShortDescription: "sample Energy Bars",
    id: "2",
    catagory: "PackedFood",
    ingredients: "nuts, honey, oats",
    nutritionalInformation: "calories: 131, protien: 5.5g, carbs: 25g",
    Amount: "500g",
    PackageType: "Bag",
    SupplierName: "ener",
    Origin: "ethiopia",
  },
  {
    foodName: "Caned Fish",
    image: require("../../assets/images/CannedFish.png"),
    Price: 20,
    DiscountPrice: 15,
    Rating: "4.5 of 5 stars)",
    NumberofReviews: "200",
    ShortDescription: "sample Caned fish",
    id: "3",
    catagory: "PackedFood",
    ingredients: "fish, oil, salt",
    nutritionalInformation: "calories: 131, protien: 5.5g, carbs: 25g",
    Amount: "500g",
    PackageType: "Bag",
    SupplierName: "fish",
    Origin: "ethiopia",
  },
  {
    foodName: " chocolate chips",
    image: require("../../assets/images/chocolateChips.png"),
    Price: 20,
    DiscountPrice: 15,
    Rating: "4.5 of 5 stars)",
    NumberofReviews: "200",
    ShortDescription: "sample  chocolate chips",
    id: "4",
    catagory: "PackedFood",
    ingredients: "chocolate, sugar, flour",
    nutritionalInformation: "calories: 131, protien: 5.5g, carbs: 25g",
    Amount: "500g",
    PackageType: "Bag",
    SupplierName: "choco",
    Origin: "ethiopia",
  },
];

export const SoftDrinkCategory = [
  {
    drinkName: "Coca Cola",
    image: require("../../assets/images/Coca-Cola.png"),
    Price: 20,
    DiscountPrice: 15,
    Rating: "4.5 of 5 stars)",
    NumberofReviews: "200",
    ShortDescription: "sample coca cola",
    id: "0",
    catagory: "SoftDrink",
    ingredients: "sugar, water, caramel",
    nutritionalInformation: "calories: 140, protien: 0g, carbs: 39g",
    Amount: "500ml",
    PackageType: "Bottle",
    SupplierName: "coca",
    Origin: "ethiopia",
  },
  {
    drinkName: "Fanta ",
    image: require("../../assets/images/Fanta .png"),
    Price: 20,
    DiscountPrice: 15,
    Rating: "4.5 of 5 stars)",
    NumberofReviews: "200",
    ShortDescription: "sample Fanta ",
    id: "1",
    catagory: "SoftDrink",
    ingredients: "sugar, water, caramel",
    nutritionalInformation: "calories: 140, protien: 0g, carbs: 39g",
    Amount: "500ml",
    PackageType: "Bottle",
    SupplierName: "fan",
    Origin: "ethiopia",
  },
  {
    drinkName: "Sprite",
    image: require("../../assets/images/Sprite.png"),
    Price: 20,
    DiscountPrice: 15,
    Rating: "4.5 of 5 stars)",
    NumberofReviews: "200",
    ShortDescription: "sample Sprite",
    id: "2",
    catagory: "SoftDrink",
    ingredients: "sugar, water, caramel",
    nutritionalInformation: "calories: 140, protien: 0g, carbs: 39g",
    Amount: "500ml",
    PackageType: "Bottle",
    SupplierName: "spir",
    Origin: "ethiopia",
  },
  {
    drinkName: "Pepsi",
    image: require("../../assets/images/Pepsi.png"),
    Price: 20,
    DiscountPrice: 15,
    Rating: "4.5 of 5 stars)",
    NumberofReviews: "200",
    ShortDescription: "sample Pepsi ",
    id: "3",
    catagory: "SoftDrink",
    ingredients: "sugar, water, caramel",
    nutritionalInformation: "calories: 140, protien: 0g, carbs: 39g",
    Amount: "500ml",
    PackageType: "Bottle",
    SupplierName: "peps",
    Origin: "ethiopia",
  },
];

export const CosmoticsCategory = [
  {
    cosmoticsName: "Lipstick",
    image: require("../../assets/images/Lipstick.jpeg"),
    Price: 20,
    DiscountPrice: 15,
    Rating: "4.5 of 5 stars)",
    NumberofReviews: "200",
    ShortDescription: "sample Lipstick",
    id: "0",
    catagory: "Cosmotics",
    ingredients: "wax, oil, pigment",
    nutritionalInformation: "calories: 0, protien: 0g, carbs: 0g",
    Amount: "10g",
    PackageType: "Tube",
    SupplierName: "lips",
    Origin: "ethiopia",
  },
  {
    cosmoticsName: "Prilimer ",
    image: require("../../assets/images/Primer.jpeg"),
    Price: 20,
    DiscountPrice: 15,
    Rating: "4.5 of 5 stars)",
    NumberofReviews: "200",
    ShortDescription: "sample Prilimer ",
    id: "1",
    catagory: "Cosmotics",
    ingredients: "wax, oil, pigment",
    nutritionalInformation: "calories: 0, protien: 0g, carbs: 0g",
    Amount: "10g",
    PackageType: "Tube",
    SupplierName: "prim",
    Origin: "ethiopia",
  },
  {
    cosmoticsName: "Foundation",
    image: require("../../assets/images/Foundation.jpeg"),
    Price: 20,
    DiscountPrice: 15,
    Rating: "4.5 of 5 stars)",
    NumberofReviews: "200",
    ShortDescription: "sample Foundation",
    id: "2",
    catagory: "Cosmotics",
    ingredients: "wax, oil, pigment",
    nutritionalInformation: "calories: 0, protien: 0g, carbs: 0g",
    Amount: "10g",
    PackageType: "Tube",
    SupplierName: "foun",
    Origin: "ethiopia",
  },
  {
    cosmoticsName: "Concealer",
    image: require("../../assets/images/Concealer.jpeg"),
    Price: 20,
    DiscountPrice: 15,
    Rating: "4.5 of 5 stars)",
    NumberofReviews: "200",
    ShortDescription: "sample Concealer ",
    id: "3",
    catagory: "Cosmotics",
    ingredients: "wax, oil, pigment",
    nutritionalInformation: "calories: 0, protien: 0g, carbs: 0g",
    Amount: "10g",
    PackageType: "Tube",
    SupplierName: "conc",
    Origin: "ethiopia",
  },
  {
    cosmoticsName: "Mascara",
    image: require("../../assets/images/Mascara.jpeg"),
    Price: 20,
    DiscountPrice: 15,
    Rating: "4.5 of 5 stars)",
    NumberofReviews: "200",
    ShortDescription: "sample Mascara ",
    id: "4",
    catagory: "Cosmotics",
    ingredients: "wax, oil, pigment",
    nutritionalInformation: "calories: 0, protien: 0g, carbs: 0g",
    Amount: "10g",
    PackageType: "Tube",
    SupplierName: "masc",
    Origin: "ethiopia",
  },
];

export const AlcholicDrinkCategory = [
  {
    AlcholName: "Beer",
    image: require("../../assets/images/Beer.png"),
    Price: 20,
    DiscountPrice: 15,
    Rating: "4.5 of 5 stars)",
    NumberofReviews: "200",
    ShortDescription: "sample Beer",
    id: "0",
    catagory: "AlcholicDrink",
    ingredients: "barley, water, hops, yeast",
    nutritionalInformation: "calories: 43, protien: 0.5g, carbs: 3.6g",
    Amount: "500ml",
    PackageType: "Bottle",
    SupplierName: "dashen",
    Origin: "ethiopia",
  },
  {
    AlcholName: "Wine ",
    image: require("../../assets/images/Wine.jpeg"),
    Price: 20,
    DiscountPrice: 15,
    Rating: "4.5 of 5 stars)",
    NumberofReviews: "200",
    ShortDescription: "sample Wine ",
    id: "1",
    catagory: "AlcholicDrink",
    ingredients: "grapes, yeast",
    nutritionalInformation: "calories: 83, protien: 0.1g, carbs: 2.6g",
    Amount: "500ml",
    PackageType: "Bottle",
    SupplierName: "wine",
    Origin: "ethiopia",
  },
  {
    AlcholName: "Vodka",
    image: require("../../assets/images/Vodka.jpeg"),
    Price: 20,
    DiscountPrice: 15,
    Rating: "4.5 of 5 stars)",
    NumberofReviews: "200",
    ShortDescription: "sample Vodka",
    id: "2",
    catagory: "AlcholicDrink",
    ingredients: "grains, water, yeast",
    nutritionalInformation: "calories: 231, protien: 0g, carbs: 0g",
    Amount: "500ml",
    PackageType: "Bottle",
    SupplierName: "vodka",
    Origin: "ethiopia",
  },
  {
    AlcholName: "Gin",
    image: require("../../assets/images/Gin.jpeg"),
    Price: 20,
    DiscountPrice: 15,
    Rating: "4.5 of 5 stars)",
    NumberofReviews: "200",
    ShortDescription: "sample Gin ",
    id: "3",
    catagory: "AlcholicDrink",
    ingredients: "grains, water, yeast",
    nutritionalInformation: "calories: 231, protien: 0g, carbs: 0g",
    Amount: "500ml",
    PackageType: "Bottle",
    SupplierName: "gin",
    Origin: "ethiopia",
  },
  {
    AlcholName: "Whisky",
    image: require("../../assets/images/Whisky.jpeg"),
    Price: 20,
    DiscountPrice: 15,
    Rating: "4.5 of 5 stars)",
    NumberofReviews: "200",
    ShortDescription: "sample Whisky ",
    id: "4",
    catagory: "AlcholicDrink",
    ingredients: "grains, water, yeast",
    nutritionalInformation: "calories: 231, protien: 0g, carbs: 0g",
    Amount: "500ml",
    PackageType: "Bottle",
    SupplierName: "whis",
    Origin: "ethiopia",
  },
];
export const customer = [
  {
    id: 1,
    userName: "menga",
    firstName: "Mengaw",
    lastName: "Wubetu",
    phone: "0963760376",
    address: "wku",
    password: "12345678",
  },
  {
    id: 2,
    userName: "meng",
    firstName: "Menga",
    lastName: "Wube",
    phone: "0963760376",
    address: "wku",
    password: "12345678",
  },
  {
    id: 3,
    userName: "meski",
    firstName: "Meskerem",
    lastName: "Degu",
    phone: "0963760376",
    address: "wku",
    password: "12345678",
  },
  {
    id: 4,
    userName: "hikma",
    firstName: "Hikma",
    lastName: "Mohamed",
    phone: "0963760376",
    address: "wku",
    password: "12345678",
  },
  {
    id: 5,
    userName: "aby",
    firstName: "Aby",
    lastName: "Andargie",
    phone: "0963760376",
    address: "wku",
    password: "12345678",
  },
  {
    id: 6,
    userName: "yihun",
    firstName: "Yihune",
    lastName: "Tarekegn",
    phone: "0963760376",
    address: "wku",
    password: "12345678",
  },
  {
    id: 7,
    userName: "abe",
    firstName: "Abebe",
    lastName: "Kebede",
    phone: "0963760376",
    address: "wku",
    password: "12345678",
  },
  {
    id: 8,
    userName: "urag",
    firstName: "Urague",
    lastName: "Neberu",
    phone: "0963760376",
    address: "wku",
    password: "12345678",
  },
  {
    id: 9,
    userName: "mana",
    firstName: "mengaw",
    lastName: "Wube",
    phone: "0963760376",
    address: "wku",
    password: "12345678",
  },
];
export const deliveryAgents = [
  {
    id: "1",
    firstName: "Mengaw",
    lastName: "Wubetu",
    phone: "0963760376",
    status: "available",
    rating: 4.8,
    completedOrders: 120,
  },
  {
    id: "2",
    firstName: "Menga",
    lastName: "Wubetu",
    phone: "0963760376",
    status: "busy",
    rating: 4.5,
    completedOrders: 98,
  },
  {
    id: "3",
    firstName: "Meng",
    lastName: "Wube",
    phone: "0963760376",
    status: "unavailable",
    rating: 4.2,
    completedOrders: 76,
  },
  {
    id: "4",
    firstName: "Meskerem",
    lastName: "Degu",
    phone: "0963760376",
    status: "available",
    rating: 4.9,
    completedOrders: 150,
  },
  {
    id: "5",
    firstName: "Hikma",
    lastName: "Mohamed",
    phone: "0963760376",
    status: "busy",
    rating: 4.6,
    completedOrders: 110,
  },
  {
    id: "6",
    firstName: "Abebe",
    lastName: "Lama",
    phone: "0963760376",
    status: "unavailable",
    rating: 4.0,
    completedOrders: 67,
  },
  {
    id: "7",
    firstName: "Kebade",
    lastName: "Abebe",
    phone: "0963760376",
    status: "available",
    rating: 4.7,
    completedOrders: 135,
  },
  {
    id: "8",
    firstName: "Alemitu",
    lastName: "Alemu",
    phone: "0963760376",
    status: "busy",
    rating: 4.3,
    completedOrders: 90,
  },
];
export const deliveryOrders = [
  {
    id: "101",
    customer: "John Doe",
    address: "Addis Ababa",
    status: "pending",
  },
  {
    id: "102",
    customer: "Jane Smith",
    address: "Bahir Dar",
    status: "pending",
  },
  {
    id: "103",
    customer: "Michael Tesfaye",
    address: "Adama",
    status: "pending",
  },
  { id: "104", customer: "Sarah Ali", address: "Hawassa", status: "pending" },
];
