export const promoCategories = [
  {
    ProductName: "Soft drink",
    image: require("../../assets/images/softDrink.jpeg"),
    Price: 20,
    DiscountPrice: 15,
    Rating: "4.5 of 5 stars",
    NumberofReviews: "200",
    ShortDescription: "sample discription",
    id: "0",
  },
  {
    ProductName: "Alcholic drink",
    image: require("../../assets/images/alcolicDirnk.jpeg"),
    Price: 20,
    DiscountPrice: 15,
    Rating: "4.5 of 5 stars",
    NumberofReviews: "200",
    ShortDescription: "sample discription",
    id: "1",
  },
  {
    ProductName: "Vegetable",
    image: require("../../assets/images/vegetable.jpeg"),
    Price: 20,
    DiscountPrice: 15,
    Rating: "4.5 of 5 stars",
    NumberofReviews: "200",
    ShortDescription: "sample discription",
    id: "2",
  },
  {
    ProductName: "Pcked food",
    image: require("../../assets/images/packedfood.jpeg"),
    Price: 20,
    DiscountPrice: 15,
    Rating: "4.5 of 5 stars",
    NumberofReviews: "200",
    ShortDescription: "sample discription",
    id: "3",
  },
  {
    ProductName: "cosmotics",
    image: require("../../assets/images/cosmotics.jpeg"),
    Price: 20,
    DiscountPrice: 15,
    Rating: "4.5 of 5 stars",
    NumberofReviews: "200",
    ShortDescription: "sample discription",
    id: "4",
  },
  {
    ProductName: "Fruit",
    image: require("../../assets/images/fruit.jpeg"),
    Price: 20,
    DiscountPrice: 15,
    Rating: "4.5 of 5 stars",
    NumberofReviews: "200",
    ShortDescription: "sample discription",
    id: "5",
  },
];

export const standard = [
  {
    ProductName: "Soft drink",
    image: require("../../assets/images/softDrink.jpeg"),
    Price: 20,
    DiscountPrice: 15,
    Rating: "4.5 of 5 stars",
    NumberofReviews: "200",
    ShortDescription: "sample discription",
    id: "0",
  },
  {
    ProductName: "Alcholic drink",
    image: require("../../assets/images/alcolicDirnk.jpeg"),
    Price: 20,
    DiscountPrice: 15,
    Rating: "4.5 of 5 stars",
    NumberofReviews: "200",
    ShortDescription: "sample discription",
    id: "1",
  },
  {
    ProductName: "Vegetable",
    image: require("../../assets/images/vegetable.jpeg"),
    Price: 20,
    DiscountPrice: 15,
    Rating: "4.5 of 5 stars",
    NumberofReviews: "200",
    ShortDescription: "sample discription",
    id: "2",
  },
  {
    ProductName: "Pcked food",
    image: require("../../assets/images/packedfood.jpeg"),
    Price: 20,
    DiscountPrice: 15,
    Rating: "4.5 of 5 stars",
    NumberofReviews: "200",
    ShortDescription: "sample discription",
    id: "3",
  },
  {
    ProductName: "cosmotics",
    image: require("../../assets/images/cosmotics.jpeg"),
    Price: 20,
    DiscountPrice: 15,
    Rating: "4.5 of 5 stars",
    NumberofReviews: "200",
    ShortDescription: "sample discription",
    id: "4",
  },
];
export const recomended = [
  {
    ProductName: "Soft drink",
    image: require("../../assets/images/softDrink.jpeg"),
    Price: 20,
    DiscountPrice: 15,
    Rating: "4.5 of 5 stars)",
    NumberofReviews: "200",
    ShortDescription: "sample discription",
    id: "0",
  },
  {
    ProductName: "Alcholic drink",
    image: require("../../assets/images/alcolicDirnk.jpeg"),
    Price: 20,
    DiscountPrice: 15,
    Rating: "4.5 of 5 stars",
    NumberofReviews: "200",
    ShortDescription: "sample discription",
    id: "1",
  },
  {
    ProductName: "Vegetable",
    image: require("../../assets/images/vegetable.jpeg"),
    Price: 20,
    DiscountPrice: 15,
    Rating: "4.5 of 5 stars",
    NumberofReviews: "200",
    ShortDescription: "sample discription",
    id: "2",
  },
  {
    ProductName: "Pcked food",
    image: require("../../assets/images/packedfood.jpeg"),
    Price: 20,
    DiscountPrice: 15,
    Rating: "4.5 of 5 stars",
    NumberofReviews: "200",
    ShortDescription: "sample discription",
    id: "3",
  },
  {
    ProductName: "cosmotics",
    image: require("../../assets/images/cosmotics.jpeg"),
    Price: 20,
    DiscountPrice: 15,
    Rating: "4.5 of 5 stars",
    NumberofReviews: "200",
    ShortDescription: "sample discription",
    id: "4",
  },
];

export const VegetableCategory = [
  {
    VegetableName: "Onions",
    image: require("../../assets/images/Onions.png"),
    Price: 20,
    DiscountPrice: 15,
    Rating: "4.5 of 5 stars)",
    NumberofReviews: "200",
    ShortDescription: "sample Onions",
    id: "0",
  },
  {
    VegetableName: "cabbage",
    image: require("../../assets/images/Cabbage.jpeg"),
    Price: 20,
    DiscountPrice: 15,
    Rating: "4.5 of 5 stars)",
    NumberofReviews: "200",
    ShortDescription: "sample cabbage",
    id: "1",
  },
  {
    VegetableName: "carot",
    image: require("../../assets/images/carot.jpeg"),
    Price: 20,
    DiscountPrice: 15,
    Rating: "4.5 of 5 stars)",
    NumberofReviews: "200",
    ShortDescription: "sample carot",
    id: "2",
  },
  {
    VegetableName: "tomato",
    image: require("../../assets/images/tomato.jpeg"),
    Price: 20,
    DiscountPrice: 15,
    Rating: "4.5 of 5 stars)",
    NumberofReviews: "200",
    ShortDescription: "sample tomato",
    id: "3",
  },
  {
    VegetableName: "potato",
    image: require("../../assets/images/Potatoes.png"),
    Price: 20,
    DiscountPrice: 15,
    Rating: "4.5 of 5 stars)",
    NumberofReviews: "200",
    ShortDescription: "sample potato",
    id: "5",
  },
];

export const FruitCategiry = [
  {
    VegetableName: "mango",
    image: require("../../assets/images/mango.png"),
    Price: 20,
    DiscountPrice: 15,
    Rating: "4.5 of 5 stars)",
    NumberofReviews: "200",
    ShortDescription: "sample mango",
    id: "0",
  },
  {
    VegetableName: "orange",
    image: require("../../assets/images/orange.png"),
    Price: 20,
    DiscountPrice: 15,
    Rating: "4.5 of 5 stars)",
    NumberofReviews: "200",
    ShortDescription: "sample orange",
    id: "1",
  },
  {
    VegetableName: "Lemon",
    image: require("../../assets/images/lemon.jpeg"),
    Price: 20,
    DiscountPrice: 15,
    Rating: "4.5 of 5 stars)",
    NumberofReviews: "200",
    ShortDescription: "sample Lemon",
    id: "2",
  },
  {
    VegetableName: "papaya",
    image: require("../../assets/images/Papaya.png"),
    Price: 20,
    DiscountPrice: 15,
    Rating: "4.5 of 5 stars)",
    NumberofReviews: "200",
    ShortDescription: "sample papaya",
    id: "3",
  },
  {
    VegetableName: "Banana",
    image: require("../../assets/images/Banana.jpeg"),
    Price: 20,
    DiscountPrice: 15,
    Rating: "4.5 of 5 stars)",
    NumberofReviews: "200",
    ShortDescription: "sample Banana",
    id: "4",
  },
];

export const PackedFoodCategory = [
  {
    VegetableName: "Pasta",
    image: require("../../assets/images/pasta.png"),
    Price: 20,
    DiscountPrice: 15,
    Rating: "4.5 of 5 stars)",
    NumberofReviews: "200",
    ShortDescription: "sample pasta",
    id: "0",
  },
  {
    VegetableName: "Biscuit",
    image: require("../../assets/images/Biscuits.png"),
    Price: 20,
    DiscountPrice: 15,
    Rating: "4.5 of 5 stars)",
    NumberofReviews: "200",
    ShortDescription: "sample biscuit",
    id: "1",
  },
  {
    VegetableName: "Energy Bars",
    image: require("../../assets/images/EnergyBars.png"),
    Price: 20,
    DiscountPrice: 15,
    Rating: "4.5 of 5 stars)",
    NumberofReviews: "200",
    ShortDescription: "sample Energy Bars",
    id: "2",
  },
  {
    VegetableName: "Caned Fish",
    image: require("../../assets/images/CannedFish.png"),
    Price: 20,
    DiscountPrice: 15,
    Rating: "4.5 of 5 stars)",
    NumberofReviews: "200",
    ShortDescription: "sample Caned fish",
    id: "3",
  },
  {
    VegetableName: " chocolate chips",
    image: require("../../assets/images/chocolateChips.png"),
    Price: 20,
    DiscountPrice: 15,
    Rating: "4.5 of 5 stars)",
    NumberofReviews: "200",
    ShortDescription: "sample  chocolate chips",
    id: "4",
  },
];

export const SoftDrinkCategory = [
  {
    VegetableName: "Coca Cola",
    image: require("../../assets/images/Coca-Cola.png"),
    Price: 20,
    DiscountPrice: 15,
    Rating: "4.5 of 5 stars)",
    NumberofReviews: "200",
    ShortDescription: "sample coca cola",
    id: "0",
  },
  {
    VegetableName: "Fanta ",
    image: require("../../assets/images/Fanta .png"),
    Price: 20,
    DiscountPrice: 15,
    Rating: "4.5 of 5 stars)",
    NumberofReviews: "200",
    ShortDescription: "sample Fanta ",
    id: "1",
  },
  {
    VegetableName: "Sprite",
    image: require("../../assets/images/Sprite.png"),
    Price: 20,
    DiscountPrice: 15,
    Rating: "4.5 of 5 stars)",
    NumberofReviews: "200",
    ShortDescription: "sample Sprite",
    id: "2",
  },
  {
    VegetableName: "Pepsi",
    image: require("../../assets/images/Pepsi.png"),
    Price: 20,
    DiscountPrice: 15,
    Rating: "4.5 of 5 stars)",
    NumberofReviews: "200",
    ShortDescription: "sample Pepsi ",
    id: "3",
  },
];

export const CosmoticsCategory = [
  {
    VegetableName: "Lipstick",
    image: require("../../assets/images/Lipstick.jpeg"),
    Price: 20,
    DiscountPrice: 15,
    Rating: "4.5 of 5 stars)",
    NumberofReviews: "200",
    ShortDescription: "sample Lipstick",
    id: "0",
  },
  {
    VegetableName: "Prilimer ",
    image: require("../../assets/images/Primer.jpeg"),
    Price: 20,
    DiscountPrice: 15,
    Rating: "4.5 of 5 stars)",
    NumberofReviews: "200",
    ShortDescription: "sample Prilimer ",
    id: "1",
  },
  {
    VegetableName: "Foundation",
    image: require("../../assets/images/Foundation.jpeg"),
    Price: 20,
    DiscountPrice: 15,
    Rating: "4.5 of 5 stars)",
    NumberofReviews: "200",
    ShortDescription: "sample Foundation",
    id: "2",
  },
  {
    VegetableName: "Concealer",
    image: require("../../assets/images/Concealer.jpeg"),
    Price: 20,
    DiscountPrice: 15,
    Rating: "4.5 of 5 stars)",
    NumberofReviews: "200",
    ShortDescription: "sample Concealer ",
    id: "3",
  },
  {
    VegetableName: "Mascara",
    image: require("../../assets/images/Mascara.jpeg"),
    Price: 20,
    DiscountPrice: 15,
    Rating: "4.5 of 5 stars)",
    NumberofReviews: "200",
    ShortDescription: "sample Mascara ",
    id: "4",
  },
];

export const AlcholicDrinkCategory = [
  {
    AlcholName: "Beer",
    image: require("../../assets/images/Beer.png"),
    Price: 20,
    DiscountPrice: 15,
    Rating: "4.5 of 5 stars)",
    NumberofReviews: "200",
    ShortDescription: "sample Beer",
    id: "0",
    catagory: "AlcholicDrink",
    ingredients: "barley, water, hops, yeast",
    nutritionalInformation: "calories: 43, protien: 0.5g, carbs: 3.6g",
    Amount: "500ml",
    PackageType: "Bottle",
    SupplierName: "dashen",
    Origin: "ethiopia",
  },
  {
    VegetableName: "Wine ",
    image: require("../../assets/images/Wine.jpeg"),
    Price: 20,
    DiscountPrice: 15,
    Rating: "4.5 of 5 stars)",
    NumberofReviews: "200",
    ShortDescription: "sample Wine ",
    id: "1",
  },
  {
    VegetableName: "Vodka",
    image: require("../../assets/images/Vodka.jpeg"),
    Price: 20,
    DiscountPrice: 15,
    Rating: "4.5 of 5 stars)",
    NumberofReviews: "200",
    ShortDescription: "sample Vodka",
    id: "2",
  },
  {
    VegetableName: "Gin",
    image: require("../../assets/images/Gin.jpeg"),
    Price: 20,
    DiscountPrice: 15,
    Rating: "4.5 of 5 stars)",
    NumberofReviews: "200",
    ShortDescription: "sample Gin ",
    id: "3",
  },
  {
    VegetableName: "Whisky",
    image: require("../../assets/images/Whisky.jpeg"),
    Price: 20,
    DiscountPrice: 15,
    Rating: "4.5 of 5 stars)",
    NumberofReviews: "200",
    ShortDescription: "sample Whisky ",
    id: "4",
  },
];
