import React from "react";
export const categories = [
  {
    categoryId: 1,
    categoryName: "Fruit & Vegetable",
    description: "sourced from farms.",
    image: require("../../assets/images/fruits.jpg"),
    status: "Active",
    numberOfProducts: 120,
    popularProducts: ["Bananas", "Tomatoes", "Carrots"],
    discountAvailable: true,
    specialOffers: "Buy 1 Get 1 Free",
    dateAdded: "2025-02-08T10:30:00Z",
    lastUpdated: "2025-02-10T14:20:00Z",
    addedBy: "Stock Manager",
  },

  {
    categoryId: 2,
    categoryName: "Dairy & Eggs",
    description: "Milk,cheese,butter, and eggs.",
    image: require("../../assets/images/Dairy-products.jpg"),
    status: "Active",
    numberOfProducts: 80,
    popularProducts: ["Whole Milk", "Cheddar Cheese", "Organic Eggs"],
    discountAvailable: false,
    specialOffers: "None",
    dateAdded: "2025-02-08T11:00:00Z",
    lastUpdated: "2025-02-09T16:45:00Z",
    addedBy: "Manager",
  },
  {
    categoryId: 3,
    categoryName: "Meat & Seafood",
    description: "Fresh,frozen meats,seafood.",
    image: require("../../assets/images/meat.jpg"),
    status: "Active",
    numberOfProducts: 65,
    popularProducts: ["Chicken Breast", "Salmon Fillet", "Beef Steak"],
    discountAvailable: true,
    specialOffers: "10% Off on All Items",
    dateAdded: "2025-02-08T12:15:00Z",
    lastUpdated: "2025-02-11T09:30:00Z",
    addedBy: "Stock Manager",
  },
  {
    categoryId: 4,
    categoryName: "Bakery",
    description: "Bread,pastries,baked goods.",
    image: require("../../assets/images/bakery.jpg"),
    status: "Active",
    numberOfProducts: 45,
    popularProducts: ["Whole Wheat Bread", "Croissants", "Muffins"],
    discountAvailable: false,
    specialOffers: "None",
    dateAdded: "2025-02-08T13:45:00Z",
    lastUpdated: "2025-02-10T15:00:00Z",
    addedBy: "Manager",
  },
  {
    categoryId: 5,
    categoryName: "Beverages",
    description: "Soft drinks, juices",
    image: require("../../assets/images/beverages.jpg"),
    status: "Active",
    numberOfProducts: 90,
    popularProducts: ["Orange Juice", "Cola", "Green Tea"],
    discountAvailable: true,
    specialOffers: "Buy 2 Get 1 Free",
    dateAdded: "2025-02-08T14:10:00Z",
    lastUpdated: "2025-02-12T10:30:00Z",
    addedBy: "Stock Manager",
  },
  {
    categoryId: 6,
    categoryName: "Pantry Essentials",
    description: "Rice,pasta,canned,goods,cooking.",
    image: require("../../assets/images/Pantry-Essentials.png"),
    status: "Active",
    numberOfProducts: 150,
    popularProducts: ["Brown Rice", "Pasta", "Canned Beans"],
    discountAvailable: false,
    specialOffers: "None",
    dateAdded: "2025-02-08T15:20:00Z",
    lastUpdated: "2025-02-09T18:10:00Z",
    addedBy: "Manager",
  },
  {
    categoryId: 7,
    categoryName: "Frozen Foods",
    description: "Frozen vegetables,snacks,ready-to-eat.",
    image: require("../../assets/images/Frozen-Foods.jpg"),
    status: "Active",
    numberOfProducts: 70,
    popularProducts: ["Frozen Peas", "Pizza", "Ice Cream"],
    discountAvailable: true,
    specialOffers: "15% Off on Select Items",
    dateAdded: "2025-02-08T16:40:00Z",
    lastUpdated: "2025-02-10T17:30:00Z",
    addedBy: "Stock Manager",
  },
  {
    categoryId: 8,
    categoryName: "Personal Care",
    description: "Hygiene and personal care products.",
    image: require("../../assets/images/personal care.jpg"),
    status: "Active",
    numberOfProducts: 55,
    popularProducts: ["Shampoo", "Toothpaste", "Body Wash"],
    discountAvailable: false,
    specialOffers: "None",
    dateAdded: "2025-02-08T17:55:00Z",
    lastUpdated: "2025-02-11T11:40:00Z",
    addedBy: "Manager",
  },
];
export const products = [
  {
    productId: 101,
    productName: "Bananas",
    categoryId: 1,
    categoryName: "Fresh Produce",
    description: "Fresh and organic bananas sourced from local farms.",
    image: require("../../assets/images/bananas.png"),
    price: 2.99,
    discountPrice: 2.49,
    stockQuantity: 200,
    unitType: "kg",
    brand: "Local Farm",
    supplier: "Green Farms Ltd.",
    status: "Active",
    dateAdded: "2025-02-08T10:45:00Z",
    lastUpdated: "2025-02-10T14:00:00Z",
    productionDate: "2025-02-05",
    expirationDate: "2025-02-20",
    bestSeller: true,
    ratings: 4.5,
    numberOfReviews: 120,
    specialOffers: "Buy 1 Get 1 Free",
    addedBy: "Stock Manager",
    
  },
  {
    productId: 102,
    productName: "Tomatoes",
    categoryId: 1,
    categoryName: "Fresh Produce",
    description: "Ripe and juicy red tomatoes.",
    image: require("../../assets/images/tomato.png"),
    price: 3.49,
    discountPrice: 3.19,
    stockQuantity: 150,
    unitType: "kg",
    brand: "Organic Farms",
    supplier: "AgroFresh Suppliers",
    status: "Active",
    dateAdded: "2025-02-08T11:15:00Z",
    lastUpdated: "2025-02-10T14:30:00Z",
    productionDate: "2025-02-06",
    expirationDate: "2025-02-18",
    bestSeller: true,
    ratings: 4.3,
    numberOfReviews: 95,
    specialOffers: "10% Off",
    addedBy: "Stock Manager",
  },
  {
    productId: 103,
    productName: "Carrots",
    categoryId: 1,
    categoryName: "Fresh Produce",
    description: "Crisp and sweet organic carrots.",
    image: require("../../assets/images/carrot.png"),
    price: 2.79,
    discountPrice: 2.39,
    stockQuantity: 180,
    unitType: "kg",
    brand: "Farm Fresh",
    supplier: "Green Fields Ltd.",
    status: "Active",
    dateAdded: "2025-02-08T12:00:00Z",
    lastUpdated: "2025-02-10T15:00:00Z",
    productionDate: "2025-02-04",
    expirationDate: "2025-02-22",
    bestSeller: false,
    ratings: 4.6,
    numberOfReviews: 85,
    specialOffers: "None",
    addedBy: "Manager",
  },
  {
    productId: 104,
    productName: "Spinach",
    categoryId: 1,
    categoryName: "Fresh Produce",
    description: "Fresh and nutrient-rich spinach leaves.",
    image: require("../../assets/images/spinach.jpg"),
    price: 1.99,
    discountPrice: 1.79,
    stockQuantity: 120,
    unitType: "bunch",
    brand: "Nature's Green",
    supplier: "Eco Farms",
    status: "Active",
    dateAdded: "2025-02-08T13:30:00Z",
    lastUpdated: "2025-02-10T16:15:00Z",
    productionDate: "2025-02-07",
    expirationDate: "2025-02-16",
    bestSeller: false,
    ratings: 4.4,
    numberOfReviews: 60,
    specialOffers: "None",
    addedBy: "Stock Manager",
  },
  {
    productId: 105,
    productName: "Oranges",
    categoryId: 1,
    categoryName: "Fresh Produce",
    description: "Sweet and tangy oranges full of vitamin C.",
    image: require("../../assets/images/orange.png"),
    price: 4.99,
    discountPrice: 4.49,
    stockQuantity: 100,
    unitType: "kg",
    brand: "Sunshine Farms",
    supplier: "Fruit Market Ltd.",
    status: "Active",
    dateAdded: "2025-02-08T14:45:00Z",
    lastUpdated: "2025-02-10T17:00:00Z",
    productionDate: "2025-02-02",
    expirationDate: "2025-02-25",
    bestSeller: true,
    ratings: 4.7,
    numberOfReviews: 130,
    specialOffers: "Buy 2 Get 1 Free",
    addedBy: "Manager",
  },
  {
    productId: 106,
    productName: "Potatoes",
    categoryId: 1,
    categoryName: "Fresh Produce",
    description: "Versatile and fresh potatoes for cooking.",
    image: require("../../assets/images/potato.png"),
    price: 3.29,
    discountPrice: 2.99,
    stockQuantity: 250,
    unitType: "kg",
    brand: "Harvest Choice",
    supplier: "AgriSupplies Ltd.",
    status: "Active",
    dateAdded: "2025-02-08T15:30:00Z",
    lastUpdated: "2025-02-10T17:45:00Z",
    productionDate: "2025-02-03",
    expirationDate: "2025-02-28",
    bestSeller: false,
    ratings: 4.2,
    numberOfReviews: 75,
    specialOffers: "5% Off",
    addedBy: "Stock Manager",
  },
  {
    productId: 107,
    productName: "Strawberries",
    categoryId: 1,
    categoryName: "Fresh Produce",
    description: "Fresh and sweet strawberries perfect for desserts.",
    image: require("../../assets/images/strawberry.png"),
    price: 5.99,
    discountPrice: 5.49,
    stockQuantity: 80,
    unitType: "box",
    brand: "Berry Farms",
    supplier: "Fresh Picked Suppliers",
    status: "Active",
    dateAdded: "2025-02-08T16:10:00Z",
    lastUpdated: "2025-02-10T18:30:00Z",
    productionDate: "2025-02-06",
    expirationDate: "2025-02-19",
    bestSeller: true,
    ratings: 4.8,
    numberOfReviews: 160,
    specialOffers: "Buy 1 Get 1 50% Off",
    addedBy: "Manager",
  },
  {
    productId: 108,
    productName: "Cucumbers",
    categoryId: 1,
    categoryName: "Fresh Produce",
    description: "Crunchy and hydrating cucumbers.",
    image: require("../../assets/images/cucumber.png"),
    price: 2.59,
    discountPrice: 2.29,
    stockQuantity: 140,
    unitType: "kg",
    brand: "Nature's Fresh",
    supplier: "Green Valley Farms",
    status: "Active",
    dateAdded: "2025-02-08T17:00:00Z",
    lastUpdated: "2025-02-10T19:10:00Z",
    productionDate: "2025-02-07",
    expirationDate: "2025-02-21",
    bestSeller: false,
    ratings: 4.3,
    numberOfReviews: 65,
    specialOffers: "None",
    addedBy: "Stock Manager",
  },
  {
    productId: 109,
    productName: "Lettuce",
    categoryId: 1,
    categoryName: "Fresh Produce",
    description: "Crisp and refreshing lettuce leaves.",
    image: require("../../assets/images/lettuce.png"),
    price: 1.89,
    discountPrice: 1.59,
    stockQuantity: 110,
    unitType: "head",
    brand: "Healthy Greens",
    supplier: "Organic Harvest Ltd.",
    status: "Active",
    dateAdded: "2025-02-08T18:15:00Z",
    lastUpdated: "2025-02-10T19:45:00Z",
    productionDate: "2025-02-06",
    expirationDate: "2025-02-17",
    bestSeller: false,
    ratings: 4.5,
    numberOfReviews: 80,
    specialOffers: "None",
    addedBy: "Manager",
  },

  {
    productId: 201,
    productName: "Whole Milk",
    categoryId: 2,
    categoryName: "Dairy & Eggs",
    description:
      "Fresh and nutritious whole milk, perfect for daily consumption.",
    image: require("../../assets/images/WholeMilk.png"),
    price: 4.99,
    discountPrice: 4.99,
    stockQuantity: 150,
    unitType: "L",
    brand: "Dairy Fresh",
    supplier: "Pure Farms Ltd.",
    status: "Active",
    dateAdded: "2025-02-08T11:15:00Z",
    lastUpdated: "2025-02-09T16:30:00Z",
    productionDate: "2025-02-05",
    expirationDate: "2025-03-05",
    bestSeller: true,
    ratings: 4.7,
    numberOfReviews: 140,
    specialOffers: "None",
    addedBy: "Manager",
  },
  {
    productId: 202,
    productName: "Cheddar Cheese",
    categoryId: 2,
    categoryName: "Dairy & Eggs",
    description: "Rich and creamy cheddar cheese, aged to perfection.",
    image: require("../../assets/images/cheeses.png"),
    price: 6.49,
    discountPrice: 6.49,
    stockQuantity: 90,
    unitType: "500g",
    brand: "Golden Dairy",
    supplier: "Farmhouse Cheese Ltd.",
    status: "Active",
    dateAdded: "2025-02-08T12:10:00Z",
    lastUpdated: "2025-02-09T17:00:00Z",
    productionDate: "2025-01-28",
    expirationDate: "2025-04-28",
    bestSeller: false,
    ratings: 4.6,
    numberOfReviews: 110,
    specialOffers: "None",
    addedBy: "Stock Manager",
  },
  {
    productId: 203,
    productName: "Organic Eggs",
    categoryId: 2,
    categoryName: "Dairy & Eggs",
    description: "Farm-fresh organic eggs from free-range hens.",
    image: require("../../assets/images/egg.png"),
    price: 5.99,
    discountPrice: 5.99,
    stockQuantity: 200,
    unitType: "Dozen",
    brand: "Healthy Choice",
    supplier: "Nature's Egg Farm",
    status: "Active",
    dateAdded: "2025-02-08T13:30:00Z",
    lastUpdated: "2025-02-09T17:30:00Z",
    productionDate: "2025-02-07",
    expirationDate: "2025-02-28",
    bestSeller: true,
    ratings: 4.8,
    numberOfReviews: 180,
    specialOffers: "None",
    addedBy: "Manager",
  },
  {
    productId: 204,
    productName: "Salted Butter",
    categoryId: 2,
    categoryName: "Dairy & Eggs",
    description: "Creamy and rich salted butter, ideal for cooking and baking.",
    image: require("../../assets/images/butterr.png"),
    price: 3.99,
    discountPrice: 3.99,
    stockQuantity: 120,
    unitType: "250g",
    brand: "Golden Dairy",
    supplier: "Pure Farms Ltd.",
    status: "Active",
    dateAdded: "2025-02-08T14:00:00Z",
    lastUpdated: "2025-02-09T18:00:00Z",
    productionDate: "2025-02-03",
    expirationDate: "2025-06-01",
    bestSeller: false,
    ratings: 4.5,
    numberOfReviews: 85,
    specialOffers: "None",
    addedBy: "Stock Manager",
  },
  {
    productId: 205,
    productName: "Yogurt",
    categoryId: 2,
    categoryName: "Dairy & Eggs",
    description: "Thick and creamy Greek yogurt, high in protein.",
    image: require("../../assets/images/Yogurt.png"),
    price: 4.29,
    discountPrice: 4.29,
    stockQuantity: 130,
    unitType: "500g",
    brand: "Yogurt Delight",
    supplier: "Pure Dairy Ltd.",
    status: "Active",
    dateAdded: "2025-02-08T15:00:00Z",
    lastUpdated: "2025-02-09T18:30:00Z",
    productionDate: "2025-02-04",
    expirationDate: "2025-03-10",
    bestSeller: false,
    ratings: 4.6,
    numberOfReviews: 95,
    specialOffers: "None",
    addedBy: "Manager",
  },
  {
    productId: 206,
    productName: "Skim Milk",
    categoryId: 2,
    categoryName: "Dairy & Eggs",
    description: "Low-fat skim milk, rich in calcium and protein.",
    image: require("../../assets/images/SkimMilk.png"),
    price: 4.49,
    discountPrice: 4.49,
    stockQuantity: 100,
    unitType: "L",
    brand: "Dairy Fresh",
    supplier: "AgriDairy Ltd.",
    status: "Active",
    dateAdded: "2025-02-08T16:00:00Z",
    lastUpdated: "2025-02-09T19:00:00Z",
    productionDate: "2025-02-06",
    expirationDate: "2025-03-06",
    bestSeller: false,
    ratings: 4.4,
    numberOfReviews: 70,
    specialOffers: "None",
    addedBy: "Stock Manager",
  },
  {
    productId: 207,
    productName: "Parmesan Cheese",
    categoryId: 2,
    categoryName: "Dairy & Eggs",
    description: "Aged parmesan cheese with a bold and nutty flavor.",
    image: require("../../assets/images/ParmesanCheese.png"),
    price: 7.99,
    discountPrice: 7.99,
    stockQuantity: 85,
    unitType: "300g",
    brand: "Golden Dairy",
    supplier: "Cheese Haven Ltd.",
    status: "Active",
    dateAdded: "2025-02-08T17:00:00Z",
    lastUpdated: "2025-02-09T19:30:00Z",
    productionDate: "2025-01-25",
    expirationDate: "2025-06-30",
    bestSeller: false,
    ratings: 4.7,
    numberOfReviews: 125,
    specialOffers: "None",
    addedBy: "Manager",
  },
  {
    productId: 208,
    productName: "Cottage Cheese",
    categoryId: 2,
    categoryName: "Dairy & Eggs",
    description: "Soft and creamy cottage cheese, great for a healthy diet.",
    image: require("../../assets/images/CottageCheese.png"),
    price: 5.29,
    discountPrice: 5.29,
    stockQuantity: 110,
    unitType: "400g",
    brand: "Healthy Choice",
    supplier: "AgriDairy Ltd.",
    status: "Active",
    dateAdded: "2025-02-08T18:00:00Z",
    lastUpdated: "2025-02-09T20:00:00Z",
    productionDate: "2025-02-02",
    expirationDate: "2025-04-20",
    bestSeller: false,
    ratings: 4.5,
    numberOfReviews: 90,
    specialOffers: "None",
    addedBy: "Stock Manager",
  },

  {
    productId: 301,
    productName: "Chicken Breast",
    categoryId: 3,
    categoryName: "Meat & Seafood",
    description: "Fresh boneless and skinless chicken breast, high in protein.",
    image: require("../../assets/images/ChickenBreast.png"),
    price: 8.99,
    discountPrice: 8.09, // 10% off applied
    stockQuantity: 120,
    unitType: "kg",
    brand: "Farm Fresh",
    supplier: "AgroMeat Suppliers",
    status: "Active",
    dateAdded: "2025-02-08T13:00:00Z",
    lastUpdated: "2025-02-11T10:00:00Z",
    productionDate: "2025-02-07",
    expirationDate: "2025-02-14",
    bestSeller: true,
    ratings: 4.7,
    numberOfReviews: 150,
    specialOffers: "10% Off",
    addedBy: "Stock Manager",
  },
  {
    productId: 302,
    productName: "Salmon Fillet",
    categoryId: 3,
    categoryName: "Meat & Seafood",
    description: "Fresh Atlantic salmon fillet, rich in omega-3.",
    image: require("../../assets/images/SalmonFillet.png"),
    price: 15.99,
    discountPrice: 14.39, // 10% off applied
    stockQuantity: 85,
    unitType: "kg",
    brand: "Ocean Delight",
    supplier: "SeaHarvest Ltd.",
    status: "Active",
    dateAdded: "2025-02-08T14:30:00Z",
    lastUpdated: "2025-02-11T10:20:00Z",
    productionDate: "2025-02-06",
    expirationDate: "2025-02-12",
    bestSeller: true,
    ratings: 4.8,
    numberOfReviews: 120,
    specialOffers: "10% Off",
    addedBy: "Stock Manager",
  },
  {
    productId: 303,
    productName: "Beef Steak",
    categoryId: 3,
    categoryName: "Meat & Seafood",
    description: "Premium beef steak, tender and juicy for grilling.",
    image: require("../../assets/images/BeefSteak.png"),
    price: 12.99,
    discountPrice: 11.69, // 10% off applied
    stockQuantity: 100,
    unitType: "kg",
    brand: "Prime Cuts",
    supplier: "Farm Fresh Meats",
    status: "Active",
    dateAdded: "2025-02-08T15:00:00Z",
    lastUpdated: "2025-02-11T10:40:00Z",
    productionDate: "2025-02-05",
    expirationDate: "2025-02-13",
    bestSeller: true,
    ratings: 4.6,
    numberOfReviews: 110,
    specialOffers: "10% Off",
    addedBy: "Stock Manager",
  },

  {
    productId: 305,
    productName: "fish",
    categoryId: 3,
    categoryName: "Meat & Seafood",
    description: "Delicious and tender turkey drumsticks, great for roasting.",
    image: require("../../assets/images/fish.png"),
    price: 9.99,
    discountPrice: 8.99, // 10% off applied
    stockQuantity: 110,
    unitType: "kg",
    brand: "Farm Fresh",
    supplier: "AgroMeat Suppliers",
    status: "Active",
    dateAdded: "2025-02-08T17:00:00Z",
    lastUpdated: "2025-02-11T11:20:00Z",
    productionDate: "2025-02-07",
    expirationDate: "2025-02-16",
    bestSeller: false,
    ratings: 4.4,
    numberOfReviews: 80,
    specialOffers: "10% Off",
    addedBy: "Stock Manager",
  },
  {
    productId: 306,
    productName: "Pork Chops",
    categoryId: 3,
    categoryName: "Meat & Seafood",
    description: "Juicy and tender pork chops, perfect for grilling.",
    image: require("../../assets/images/PorkChops.png"),
    price: 11.99,
    discountPrice: 10.79, // 10% off applied
    stockQuantity: 95,
    unitType: "kg",
    brand: "Prime Cuts",
    supplier: "Farm Fresh Meats",
    status: "Active",
    dateAdded: "2025-02-08T18:00:00Z",
    lastUpdated: "2025-02-11T11:40:00Z",
    productionDate: "2025-02-04",
    expirationDate: "2025-02-13",
    bestSeller: false,
    ratings: 4.3,
    numberOfReviews: 70,
    specialOffers: "10% Off",
    addedBy: "Stock Manager",
  },

  {
    productId: 401,
    productName: "Whole Wheat Bread",
    categoryId: 4,
    categoryName: "Bakery",
    description: "Healthy whole wheat bread, freshly baked.",
    image: require("../../assets/images/WholeWheatBread.png"),
    price: 3.99,
    discountPrice: null,
    stockQuantity: 150,
    unitType: "loaf",
    brand: "Fresh Bakes",
    supplier: "Golden Grains Bakery",
    status: "Active",
    dateAdded: "2025-02-08T14:00:00Z",
    lastUpdated: "2025-02-10T15:30:00Z",
    productionDate: "2025-02-10",
    expirationDate: "2025-02-14",
    bestSeller: true,
    ratings: 4.8,
    numberOfReviews: 95,
    specialOffers: "None",
    addedBy: "Manager",
  },
  {
    productId: 402,
    productName: "Croissants",
    categoryId: 4,
    categoryName: "Bakery",
    description: "Buttery, flaky croissants, freshly baked daily.",
    image: require("../../assets/images/Croissants.png"),
    price: 5.49,
    discountPrice: null,
    stockQuantity: 100,
    unitType: "pack",
    brand: "French Delights",
    supplier: "Golden Grains Bakery",
    status: "Active",
    dateAdded: "2025-02-08T14:30:00Z",
    lastUpdated: "2025-02-10T15:45:00Z",
    productionDate: "2025-02-10",
    expirationDate: "2025-02-13",
    bestSeller: true,
    ratings: 4.9,
    numberOfReviews: 120,
    specialOffers: "None",
    addedBy: "Manager",
  },
  {
    productId: 403,
    productName: "Muffins",
    categoryId: 4,
    categoryName: "Bakery",
    description: "Soft and moist muffins, available in various flavors.",
    image: require("../../assets/images/Muffins.png"),
    price: 4.99,
    discountPrice: null,
    stockQuantity: 120,
    unitType: "pack",
    brand: "Sweet Treats",
    supplier: "Golden Grains Bakery",
    status: "Active",
    dateAdded: "2025-02-08T15:00:00Z",
    lastUpdated: "2025-02-10T16:00:00Z",
    productionDate: "2025-02-10",
    expirationDate: "2025-02-13",
    bestSeller: true,
    ratings: 4.7,
    numberOfReviews: 85,
    specialOffers: "None",
    addedBy: "Manager",
  },
  {
    productId: 404,
    productName: "Baguette",
    categoryId: 4,
    categoryName: "Bakery",
    description: "Crispy French baguette, perfect for sandwiches.",
    image: require("../../assets/images/Baguette.png"),
    price: 2.99,
    discountPrice: null,
    stockQuantity: 90,
    unitType: "loaf",
    brand: "French Delights",
    supplier: "Golden Grains Bakery",
    status: "Active",
    dateAdded: "2025-02-08T15:30:00Z",
    lastUpdated: "2025-02-10T16:15:00Z",
    productionDate: "2025-02-10",
    expirationDate: "2025-02-12",
    bestSeller: false,
    ratings: 4.6,
    numberOfReviews: 70,
    specialOffers: "None",
    addedBy: "Manager",
  },
  {
    productId: 405,
    productName: "Chocolate Cake",
    categoryId: 4,
    categoryName: "Bakery",
    description: "Rich and moist chocolate cake, perfect for desserts.",
    image: require("../../assets/images/ChocolateCake.png"),
    price: 14.99,
    discountPrice: null,
    stockQuantity: 60,
    unitType: "whole cake",
    brand: "Sweet Treats",
    supplier: "Golden Grains Bakery",
    status: "Active",
    dateAdded: "2025-02-08T16:00:00Z",
    lastUpdated: "2025-02-10T16:30:00Z",
    productionDate: "2025-02-09",
    expirationDate: "2025-02-13",
    bestSeller: true,
    ratings: 4.9,
    numberOfReviews: 130,
    specialOffers: "None",
    addedBy: "Manager",
  },
  {
    productId: 406,
    productName: "Donuts",
    categoryId: 4,
    categoryName: "Bakery",
    description: "Soft and fluffy donuts, available in assorted flavors.",
    image: require("../../assets/images/Donuts.png"),
    price: 6.99,
    discountPrice: null,
    stockQuantity: 110,
    unitType: "pack",
    brand: "Sweet Treats",
    supplier: "Golden Grains Bakery",
    status: "Active",
    dateAdded: "2025-02-08T16:30:00Z",
    lastUpdated: "2025-02-10T16:45:00Z",
    productionDate: "2025-02-10",
    expirationDate: "2025-02-13",
    bestSeller: false,
    ratings: 4.5,
    numberOfReviews: 60,
    specialOffers: "None",
    addedBy: "Manager",
  },
  {
    productId: 407,
    productName: "Pita Bread",
    categoryId: 4,
    categoryName: "Bakery",
    description: "Soft and fluffy pita bread, ideal for sandwiches and wraps.",
    image: require("../../assets/images/PitaBread.png"),
    price: 3.49,
    discountPrice: null,
    stockQuantity: 80,
    unitType: "pack",
    brand: "Fresh Bakes",
    supplier: "Golden Grains Bakery",
    status: "Active",
    dateAdded: "2025-02-08T17:00:00Z",
    lastUpdated: "2025-02-10T17:00:00Z",
    productionDate: "2025-02-10",
    expirationDate: "2025-02-14",
    bestSeller: false,
    ratings: 4.6,
    numberOfReviews: 55,
    specialOffers: "None",
    addedBy: "Manager",
  },
  {
    productId: 408,
    productName: "Sourdough Bread",
    categoryId: 4,
    categoryName: "Bakery",
    description:
      "Artisan sourdough bread with a crispy crust and soft interior.",
    image: require("../../assets/images/SourdoughBread.png"),

    price: 4.99,
    discountPrice: null,
    stockQuantity: 70,
    unitType: "loaf",
    brand: "Fresh Bakes",
    supplier: "Golden Grains Bakery",
    status: "Active",
    dateAdded: "2025-02-08T17:30:00Z",
    lastUpdated: "2025-02-10T17:15:00Z",
    productionDate: "2025-02-09",
    expirationDate: "2025-02-14",
    bestSeller: false,
    ratings: 4.7,
    numberOfReviews: 65,
    specialOffers: "None",
    addedBy: "Manager",
  },

  {
    productId: 501,
    productName: "Orange Juice",
    categoryId: 5,
    categoryName: "Beverages",
    description: "Freshly squeezed 100% pure orange juice.",
    image: require("../../assets/images/OrangeJuice.png"),
    price: 5.99,
    discountPrice: 5.49,
    stockQuantity: 200,
    unitType: "bottle",
    brand: "Pure Squeeze",
    supplier: "Natural Farms",
    status: "Active",
    dateAdded: "2025-02-08T14:15:00Z",
    lastUpdated: "2025-02-12T10:45:00Z",
    productionDate: "2025-02-11",
    expirationDate: "2025-03-11",
    bestSeller: true,
    ratings: 4.8,
    numberOfReviews: 150,
    specialOffers: "Buy 2 Get 1 Free",
    addedBy: "Stock Manager",
  },
  {
    productId: 502,
    productName: "Cola",
    categoryId: 5,
    categoryName: "Beverages",
    description: "Refreshing carbonated soft drink.",
    image: require("../../assets/images/Cola.png"),
    price: 1.99,
    discountPrice: 1.79,
    stockQuantity: 500,
    unitType: "can",
    brand: "Cola Classic",
    supplier: "Beverage Co.",
    status: "Active",
    dateAdded: "2025-02-08T14:30:00Z",
    lastUpdated: "2025-02-12T10:50:00Z",
    productionDate: "2025-01-25",
    expirationDate: "2025-07-25",
    bestSeller: true,
    ratings: 4.7,
    numberOfReviews: 200,
    specialOffers: "Buy 2 Get 1 Free",
    addedBy: "Stock Manager",
  },
  {
    productId: 503,
    productName: "Green Tea",
    categoryId: 5,
    categoryName: "Beverages",
    description: "Organic green tea with antioxidants.",
    image: require("../../assets/images/GreenTea.png"),
    price: 4.49,
    discountPrice: 3.99,
    stockQuantity: 300,
    unitType: "box",
    brand: "Nature's Blend",
    supplier: "Tea Masters Ltd.",
    status: "Active",
    dateAdded: "2025-02-08T14:45:00Z",
    lastUpdated: "2025-02-12T10:55:00Z",
    productionDate: "2025-02-05",
    expirationDate: "2026-02-05",
    bestSeller: true,
    ratings: 4.9,
    numberOfReviews: 180,
    specialOffers: "Buy 2 Get 1 Free",
    addedBy: "Stock Manager",
  },

  {
    productId: 505,
    productName: "Lemonade",
    categoryId: 5,
    categoryName: "Beverages",
    description: "Refreshing homemade-style lemonade.",
    image: require("../../assets/images/Lemonade.png"),
    price: 3.99,
    discountPrice: 3.49,
    stockQuantity: 180,
    unitType: "bottle",
    brand: "Citrus Fresh",
    supplier: "Natural Farms",
    status: "Active",
    dateAdded: "2025-02-08T15:15:00Z",
    lastUpdated: "2025-02-12T11:10:00Z",
    productionDate: "2025-02-10",
    expirationDate: "2025-03-10",
    bestSeller: false,
    ratings: 4.5,
    numberOfReviews: 85,
    specialOffers: "Buy 2 Get 1 Free",
    addedBy: "Stock Manager",
  },
  {
    productId: 508,
    productName: "Sparkling Water",
    categoryId: 5,
    categoryName: "Beverages",
    description: "Refreshing carbonated sparkling water.",
    image: require("../../assets/images/SparklingWater.png"),
    price: 2.49,
    discountPrice: 2.19,
    stockQuantity: 300,
    unitType: "bottle",
    brand: "Crystal Clear",
    supplier: "Aqua Fresh Ltd.",
    status: "Active",
    dateAdded: "2025-02-08T16:00:00Z",
    lastUpdated: "2025-02-12T11:40:00Z",
    productionDate: "2025-01-28",
    expirationDate: "2026-01-28",
    bestSeller: false,
    ratings: 4.5,
    numberOfReviews: 110,
    specialOffers: "Buy 2 Get 1 Free",
    addedBy: "Stock Manager",
  },

  {
    productId: 601,
    productName: "Brown Rice",
    categoryId: 6,
    categoryName: "Pantry Essentials",
    description: "Organic whole grain brown rice, rich in fiber.",
    image: require("../../assets/images/BrownRice.png"),
    price: 8.99,
    discountPrice: 8.99,
    stockQuantity: 300,
    unitType: "bag",
    brand: "Healthy Grains",
    supplier: "Organic Farms Ltd.",
    status: "Active",
    dateAdded: "2025-02-08T15:30:00Z",
    lastUpdated: "2025-02-09T18:15:00Z",
    productionDate: "2025-01-20",
    expirationDate: "2026-01-20",
    bestSeller: true,
    ratings: 4.7,
    numberOfReviews: 180,
    specialOffers: "None",
    addedBy: "Manager",
  },
  {
    productId: 602,
    productName: "Whole Wheat Pasta",
    categoryId: 6,
    categoryName: "Pantry Essentials",
    description: "Nutrient-rich whole wheat pasta for healthy meals.",
    image: require("../../assets/images/WholeWheatPasta.png"),
    price: 4.49,
    discountPrice: 4.49,
    stockQuantity: 250,
    unitType: "box",
    brand: "Pasta Delight",
    supplier: "Golden Harvest",
    status: "Active",
    dateAdded: "2025-02-08T15:40:00Z",
    lastUpdated: "2025-02-09T18:20:00Z",
    productionDate: "2025-01-25",
    expirationDate: "2026-01-25",
    bestSeller: true,
    ratings: 4.8,
    numberOfReviews: 160,
    specialOffers: "None",
    addedBy: "Manager",
  },
  {
    productId: 603,
    productName: "Canned Beans",
    categoryId: 6,
    categoryName: "Pantry Essentials",
    description: "Ready-to-eat organic canned beans, rich in protein.",
    image: require("../../assets/images/CannedBeans.png"),
    price: 2.99,
    discountPrice: 2.99,
    stockQuantity: 400,
    unitType: "can",
    brand: "Nature’s Best",
    supplier: "Green Fields",
    status: "Active",
    dateAdded: "2025-02-08T15:50:00Z",
    lastUpdated: "2025-02-09T18:25:00Z",
    productionDate: "2025-01-30",
    expirationDate: "2027-01-30",
    bestSeller: true,
    ratings: 4.6,
    numberOfReviews: 140,
    specialOffers: "None",
    addedBy: "Manager",
  },

  {
    productId: 605,
    productName: "All-Purpose Flour",
    categoryId: 6,
    categoryName: "Pantry Essentials",
    description: "Premium all-purpose flour for baking and cooking.",
    image: require("../../assets/images/All-PurposeFlour.png"),
    price: 5.99,
    discountPrice: 5.99,
    stockQuantity: 220,
    unitType: "bag",
    brand: "Baker's Choice",
    supplier: "Millennium Mills",
    status: "Active",
    dateAdded: "2025-02-08T16:15:00Z",
    lastUpdated: "2025-02-09T18:40:00Z",
    productionDate: "2025-01-22",
    expirationDate: "2026-07-22",
    bestSeller: false,
    ratings: 4.5,
    numberOfReviews: 130,
    specialOffers: "None",
    addedBy: "Manager",
  },
  {
    productId: 606,
    productName: "Granulated Sugar",
    categoryId: 6,
    categoryName: "Pantry Essentials",
    description: "Refined granulated sugar for sweetening and baking.",
    image: require("../../assets/images/GranulatedSugar.png"),
    price: 3.49,
    discountPrice: 3.49,
    stockQuantity: 300,
    unitType: "bag",
    brand: "Sweet Harvest",
    supplier: "Sugar Mills Ltd.",
    status: "Active",
    dateAdded: "2025-02-08T16:30:00Z",
    lastUpdated: "2025-02-09T18:50:00Z",
    productionDate: "2025-01-10",
    expirationDate: "2026-12-10",
    bestSeller: false,
    ratings: 4.4,
    numberOfReviews: 100,
    specialOffers: "None",
    addedBy: "Manager",
  },
  {
    productId: 607,
    productName: "Salt",
    categoryId: 6,
    categoryName: "Pantry Essentials",
    description: "Pure refined table salt for everyday cooking.",
    image: require("../../assets/images/Salt.png"),
    price: 1.99,
    discountPrice: 1.99,
    stockQuantity: 500,
    unitType: "pack",
    brand: "Fine Salt Co.",
    supplier: "Mineral Extracts Ltd.",
    status: "Active",
    dateAdded: "2025-02-08T16:45:00Z",
    lastUpdated: "2025-02-09T19:00:00Z",
    productionDate: "2025-01-05",
    expirationDate: "No Expiry",
    bestSeller: false,
    ratings: 4.6,
    numberOfReviews: 90,
    specialOffers: "None",
    addedBy: "Manager",
  },
  {
    productId: 608,
    productName: "Honey",
    categoryId: 6,
    categoryName: "Pantry Essentials",
    description: "Raw organic honey for natural sweetness.",
    image: require("../../assets/images/Honey.png"),
    price: 9.99,
    discountPrice: 9.99,
    stockQuantity: 150,
    unitType: "jar",
    brand: "Nature’s Gold",
    supplier: "Bee Farms Ltd.",
    status: "Active",
    dateAdded: "2025-02-08T17:00:00Z",
    lastUpdated: "2025-02-09T19:10:00Z",
    productionDate: "2025-01-15",
    expirationDate: "2027-01-15",
    bestSeller: true,
    ratings: 4.9,
    numberOfReviews: 220,
    specialOffers: "None",
    addedBy: "Manager",
  },

  {
    productId: 701,
    productName: "Frozen Peas",
    categoryId: 7,
    categoryName: "Frozen Foods",
    description: "Freshly frozen green peas, perfect for cooking.",
    image: require("../../assets/images/FrozenPeas.png"),
    price: 3.99,
    discountPrice: 3.39, // 15% discount applied
    stockQuantity: 250,
    unitType: "bag",
    brand: "Green Harvest",
    supplier: "Frozen Fresh Ltd.",
    status: "Active",
    dateAdded: "2025-02-08T16:45:00Z",
    lastUpdated: "2025-02-10T17:35:00Z",
    productionDate: "2025-01-10",
    expirationDate: "2026-01-10",
    bestSeller: true,
    ratings: 4.7,
    numberOfReviews: 180,
    specialOffers: "15% Off",
    addedBy: "Stock Manager",
  },
  {
    productId: 702,
    productName: "Frozen Pizza",
    categoryId: 7,
    categoryName: "Frozen Foods",
    description: "Delicious frozen pizza with cheese and toppings.",
    image: require("../../assets/images/FrozenPizza.png"),
    price: 8.99,
    discountPrice: 7.64, // 15% discount applied
    stockQuantity: 200,
    unitType: "box",
    brand: "Quick Bite",
    supplier: "Chill Foods Co.",
    status: "Active",
    dateAdded: "2025-02-08T16:50:00Z",
    lastUpdated: "2025-02-10T17:40:00Z",
    productionDate: "2025-01-15",
    expirationDate: "2025-07-15",
    bestSeller: true,
    ratings: 4.6,
    numberOfReviews: 150,
    specialOffers: "15% Off",
    addedBy: "Stock Manager",
  },
  {
    productId: 703,
    productName: "Vanilla Ice Cream",
    categoryId: 7,
    categoryName: "Frozen Foods",
    description: "Creamy vanilla ice cream made with real milk.",
    image: require("../../assets/images/VanillaIceCream.png"),
    price: 6.49,
    discountPrice: 5.52, // 15% discount applied
    stockQuantity: 180,
    unitType: "tub",
    brand: "Sweet Bliss",
    supplier: "Frozen Treats Ltd.",
    status: "Active",
    dateAdded: "2025-02-08T16:55:00Z",
    lastUpdated: "2025-02-10T17:45:00Z",
    productionDate: "2025-01-20",
    expirationDate: "2025-08-20",
    bestSeller: true,
    ratings: 4.8,
    numberOfReviews: 200,
    specialOffers: "15% Off",
    addedBy: "Stock Manager",
  },
  {
    productId: 704,
    productName: "Frozen Mixed Vegetables",
    categoryId: 7,
    categoryName: "Frozen Foods",
    description: "A mix of frozen carrots, peas, and corn.",
    image: require("../../assets/images/FrozenMixedVegetables.png"),
    price: 4.99,
    discountPrice: 4.24, // 15% discount applied
    stockQuantity: 220,
    unitType: "bag",
    brand: "Healthy Choice",
    supplier: "Frozen Fresh Ltd.",
    status: "Active",
    dateAdded: "2025-02-08T17:00:00Z",
    lastUpdated: "2025-02-10T17:50:00Z",
    productionDate: "2025-01-12",
    expirationDate: "2026-01-12",
    bestSeller: false,
    ratings: 4.5,
    numberOfReviews: 120,
    specialOffers: "15% Off",
    addedBy: "Stock Manager",
  },
  {
    productId: 705,
    productName: "Frozen Chicken Nuggets",
    categoryId: 7,
    categoryName: "Frozen Foods",
    description: "Crispy and delicious frozen chicken nuggets.",
    image: require("../../assets/images/FrozenChickenNuggets.png"),
    price: 9.49,
    discountPrice: 8.07, // 15% discount applied
    stockQuantity: 150,
    unitType: "box",
    brand: "Crispy Bites",
    supplier: "Golden Foods Ltd.",
    status: "Active",
    dateAdded: "2025-02-08T17:05:00Z",
    lastUpdated: "2025-02-10T17:55:00Z",
    productionDate: "2025-01-18",
    expirationDate: "2025-09-18",
    bestSeller: false,
    ratings: 4.6,
    numberOfReviews: 140,
    specialOffers: "15% Off",
    addedBy: "Stock Manager",
  },
  {
    productId: 706,
    productName: "Frozen French Fries",
    categoryId: 7,
    categoryName: "Frozen Foods",
    description: "Golden, crispy frozen french fries.",
    image: require("../../assets/images/FrozenFrenchFries.png"),
    price: 5.99,
    discountPrice: 5.09, // 15% discount applied
    stockQuantity: 230,
    unitType: "bag",
    brand: "Crispy Treats",
    supplier: "Frozen Delights Ltd.",
    status: "Active",
    dateAdded: "2025-02-08T17:10:00Z",
    lastUpdated: "2025-02-10T18:00:00Z",
    productionDate: "2025-01-22",
    expirationDate: "2026-02-22",
    bestSeller: false,
    ratings: 4.4,
    numberOfReviews: 110,
    specialOffers: "15% Off",
    addedBy: "Stock Manager",
  },

  {
    productId: 708,
    productName: "Frozen Berry Mix",
    categoryId: 7,
    categoryName: "Frozen Foods",
    description: "A mix of frozen blueberries, raspberries, and strawberries.",
    image: require("../../assets/images/FrozenBerryMix.png"),
    price: 7.99,
    discountPrice: 6.79, // 15% discount applied
    stockQuantity: 160,
    unitType: "bag",
    brand: "Nature's Fresh",
    supplier: "Berry Farms Ltd.",
    status: "Active",
    dateAdded: "2025-02-08T17:20:00Z",
    lastUpdated: "2025-02-10T18:10:00Z",
    productionDate: "2025-01-17",
    expirationDate: "2026-01-17",
    bestSeller: true,
    ratings: 4.9,
    numberOfReviews: 220,
    specialOffers: "15% Off",
    addedBy: "Stock Manager",
  },

  {
    productId: 801,
    productName: "Herbal Shampoo",
    categoryId: 8,
    categoryName: "Personal Care",
    description: "Nourishing herbal shampoo for healthy hair.",
    image: require("../../assets/images/HerbalShampoo.png"),
    price: 6.99,
    discountPrice: null,
    stockQuantity: 150,
    unitType: "bottle",
    brand: "Nature Care",
    supplier: "Green Essentials Ltd.",
    status: "Active",
    dateAdded: "2025-02-08T18:00:00Z",
    lastUpdated: "2025-02-11T11:45:00Z",
    productionDate: "2025-01-05",
    expirationDate: "2027-01-05",
    bestSeller: true,
    ratings: 4.7,
    numberOfReviews: 140,
    specialOffers: "None",
    addedBy: "Manager",
  },
  {
    productId: 802,
    productName: "Fluoride Toothpaste",
    categoryId: 8,
    categoryName: "Personal Care",
    description: "Whitening toothpaste with fluoride protection.",
    image: require("../../assets/images/FluorideToothpaste.png"),
    price: 3.99,
    discountPrice: null,
    stockQuantity: 180,
    unitType: "tube",
    brand: "Bright Smile",
    supplier: "Oral Care Co.",
    status: "Active",
    dateAdded: "2025-02-08T18:05:00Z",
    lastUpdated: "2025-02-11T11:50:00Z",
    productionDate: "2025-01-10",
    expirationDate: "2026-07-10",
    bestSeller: true,
    ratings: 4.6,
    numberOfReviews: 120,
    specialOffers: "None",
    addedBy: "Manager",
  },
  {
    productId: 803,
    productName: "Moisturizing Body Wash",
    categoryId: 8,
    categoryName: "Personal Care",
    description: "Gentle body wash with deep moisturization.",
    image: require("../../assets/images/MoisturizingBodyWash.png"),
    price: 5.99,
    discountPrice: null,
    stockQuantity: 140,
    unitType: "bottle",
    brand: "Skin Bliss",
    supplier: "Personal Care Essentials Ltd.",
    status: "Active",
    dateAdded: "2025-02-08T18:10:00Z",
    lastUpdated: "2025-02-11T11:55:00Z",
    productionDate: "2025-01-08",
    expirationDate: "2026-08-08",
    bestSeller: false,
    ratings: 4.5,
    numberOfReviews: 100,
    specialOffers: "None",
    addedBy: "Manager",
  },
  {
    productId: 804,
    productName: "Aloe Vera Hand Sanitizer",
    categoryId: 8,
    categoryName: "Personal Care",
    description: "Alcohol-based hand sanitizer with aloe vera.",
    image: require("../../assets/images/AloeVeraHandSanitizer.png"),
    price: 4.49,
    discountPrice: null,
    stockQuantity: 200,
    unitType: "bottle",
    brand: "Pure Hands",
    supplier: "HealthGuard Supplies",
    status: "Active",
    dateAdded: "2025-02-08T18:15:00Z",
    lastUpdated: "2025-02-11T12:00:00Z",
    productionDate: "2025-01-12",
    expirationDate: "2027-01-12",
    bestSeller: false,
    ratings: 4.6,
    numberOfReviews: 110,
    specialOffers: "None",
    addedBy: "Manager",
  },
  {
    productId: 805,
    productName: "Lavender Body Lotion",
    categoryId: 8,
    categoryName: "Personal Care",
    description: "Hydrating body lotion with lavender scent.",
    image: require("../../assets/images/LavenderBodyLotion.png"),
    price: 7.99,
    discountPrice: null,
    stockQuantity: 120,
    unitType: "bottle",
    brand: "Skin Glow",
    supplier: "Luxury Beauty Ltd.",
    status: "Active",
    dateAdded: "2025-02-08T18:20:00Z",
    lastUpdated: "2025-02-11T12:05:00Z",
    productionDate: "2025-01-07",
    expirationDate: "2027-01-07",
    bestSeller: true,
    ratings: 4.8,
    numberOfReviews: 160,
    specialOffers: "None",
    addedBy: "Manager",
  },
  {
    productId: 806,
    productName: "Men's Shaving Foam",
    categoryId: 8,
    categoryName: "Personal Care",
    description: "Smooth shaving foam for a comfortable shave.",
    image: require("../../assets/images/Men'sShavingFoam.png"),
    price: 6.49,
    discountPrice: null,
    stockQuantity: 100,
    unitType: "can",
    brand: "Gentlemen's Choice",
    supplier: "Men's Grooming Co.",
    status: "Active",
    dateAdded: "2025-02-08T18:25:00Z",
    lastUpdated: "2025-02-11T12:10:00Z",
    productionDate: "2025-01-15",
    expirationDate: "2026-12-15",
    bestSeller: false,
    ratings: 4.4,
    numberOfReviews: 90,
    specialOffers: "None",
    addedBy: "Manager",
  },
  {
    productId: 807,
    productName: "Vitamin C Face Serum",
    categoryId: 8,
    categoryName: "Personal Care",
    description: "Brightening face serum with Vitamin C.",
    image: require("../../assets/images/VitaminCFaceSerum.png"),
    price: 12.99,
    discountPrice: null,
    stockQuantity: 80,
    unitType: "bottle",
    brand: "Glow & Radiance",
    supplier: "Beauty Essentials Ltd.",
    status: "Active",
    dateAdded: "2025-02-08T18:30:00Z",
    lastUpdated: "2025-02-11T12:15:00Z",
    productionDate: "2025-01-20",
    expirationDate: "2026-07-20",
    bestSeller: false,
    ratings: 4.7,
    numberOfReviews: 130,
    specialOffers: "None",
    addedBy: "Manager",
  },
  {
    productId: 808,
    productName: "Deodorant Roll-On",
    categoryId: 8,
    categoryName: "Personal Care",
    description: "Long-lasting roll-on deodorant with fresh scent.",
    image: require("../../assets/images/DeodorantRoll-On.png"),
    price: 5.99,
    discountPrice: null,
    stockQuantity: 130,
    unitType: "bottle",
    brand: "FreshCare",
    supplier: "Body Essentials Ltd.",
    status: "Active",
    dateAdded: "2025-02-08T18:35:00Z",
    lastUpdated: "2025-02-11T12:20:00Z",
    productionDate: "2025-01-18",
    expirationDate: "2027-01-18",
    bestSeller: false,
    ratings: 4.5,
    numberOfReviews: 115,
    specialOffers: "None",
    addedBy: "Manager",
  },
];
export const customer = [
  {
    id: 1,
    userName: "menga",
    firstName: "Mengaw",
    lastName: "Wubetu",
    phone: "0963760376",
    address: "wku",
    password: "12345678",
  },
  {
    id: 2,
    userName: "meng",
    firstName: "Menga",
    lastName: "Wube",
    phone: "0963760376",
    address: "wku",
    password: "12345678",
  },
  {
    id: 3,
    userName: "meski",
    firstName: "Meskerem",
    lastName: "Degu",
    phone: "0963760376",
    address: "wku",
    password: "12345678",
  },
  {
    id: 4,
    userName: "hikma",
    firstName: "Hikma",
    lastName: "Mohamed",
    phone: "0963760376",
    address: "wku",
    password: "12345678",
  },
  {
    id: 5,
    userName: "aby",
    firstName: "Aby",
    lastName: "Andargie",
    phone: "0963760376",
    address: "wku",
    password: "12345678",
  },
  {
    id: 6,
    userName: "yihun",
    firstName: "Yihune",
    lastName: "Tarekegn",
    phone: "0963760376",
    address: "wku",
    password: "12345678",
  },
  {
    id: 7,
    userName: "abe",
    firstName: "Abebe",
    lastName: "Kebede",
    phone: "0963760376",
    address: "wku",
    password: "12345678",
  },
  {
    id: 8,
    userName: "urag",
    firstName: "Urague",
    lastName: "Neberu",
    phone: "0963760376",
    address: "wku",
    password: "12345678",
  },
  {
    id: 9,
    userName: "mana",
    firstName: "mengaw",
    lastName: "Wube",
    phone: "0963760376",
    address: "wku",
    password: "12345678",
  },
];
export const deliveryAgents = [
  {
    id: "1",
    firstName: "Mengaw",
    lastName: "Wubetu",
    phone: "0963760376",
    status: "available",
    rating: 4.8,
    completedOrders: 120,
  },
  {
    id: "2",
    firstName: "Menga",
    lastName: "Wubetu",
    phone: "0963760376",
    status: "busy",
    rating: 4.5,
    completedOrders: 98,
  },
  {
    id: "3",
    firstName: "Meng",
    lastName: "Wube",
    phone: "0963760376",
    status: "unavailable",
    rating: 4.2,
    completedOrders: 76,
  },
  {
    id: "4",
    firstName: "Meskerem",
    lastName: "Degu",
    phone: "0963760376",
    status: "available",
    rating: 4.9,
    completedOrders: 150,
  },
  {
    id: "5",
    firstName: "Hikma",
    lastName: "Mohamed",
    phone: "0963760376",
    status: "busy",
    rating: 4.6,
    completedOrders: 110,
  },
  {
    id: "6",
    firstName: "Abebe",
    lastName: "Lama",
    phone: "0963760376",
    status: "unavailable",
    rating: 4.0,
    completedOrders: 67,
  },
  {
    id: "7",
    firstName: "Kebade",
    lastName: "Abebe",
    phone: "0963760376",
    status: "available",
    rating: 4.7,
    completedOrders: 135,
  },
  {
    id: "8",
    firstName: "Alemitu",
    lastName: "Alemu",
    phone: "0963760376",
    status: "busy",
    rating: 4.3,
    completedOrders: 90,
  },
];
export const deliveryOrders = [
  {
    id: "101",
    customer: "John Doe",
    address: "Addis Ababa",
    status: "pending",
  },
  {
    id: "102",
    customer: "Jane Smith",
    address: "Bahir Dar",
    status: "pending",
  },
  {
    id: "103",
    customer: "Michael Tesfaye",
    address: "Adama",
    status: "pending",
  },
  { id: "104", customer: "Sarah Ali", address: "Hawassa", status: "pending" },
];
export const customerAssistants = [
  { id: "1", firstName: "John", lastName: "Doe", status: "available" },
  { id: "2", firstName: "Jane", lastName: "Smith", status: "busy" },
  { id: "3", firstName: "Michael", lastName: "Brown", status: "offline" },
  { id: "4", firstName: "Emily", lastName: "Johnson", status: "available" },
  { id: "5", firstName: "Chris", lastName: "Wilson", status: "busy" },
  { id: "6", firstName: "David", lastName: "Garcia", status: "offline" },
  { id: "7", firstName: "Olivia", lastName: "Martinez", status: "available" },
  { id: "8", firstName: "Sophia", lastName: "Anderson", status: "busy" },
  { id: "9", firstName: "James", lastName: "Taylor", status: "offline" },
  { id: "10", firstName: "Benjamin", lastName: "Harris", status: "available" },
];

export const customerQueries = [
  { id: "101", customer: "Alice", issue: "Late delivery", status: "pending" },
  { id: "102", customer: "Bob", issue: "Damaged product", status: "resolved" },
  { id: "103", customer: "Charlie", issue: "Wrong item", status: "pending" },
  { id: "104", customer: "Diana", issue: "Refund request", status: "pending" },
  {
    id: "105",
    customer: "Ethan",
    issue: "Payment failure",
    status: "escalated",
  },
  { id: "106", customer: "Fiona", issue: "Missing items", status: "pending" },
  {
    id: "107",
    customer: "George",
    issue: "Defective product",
    status: "resolved",
  },
  {
    id: "108",
    customer: "Hannah",
    issue: "Incorrect price",
    status: "pending",
  },
  {
    id: "109",
    customer: "Ian",
    issue: "Order not received",
    status: "escalated",
  },
  { id: "110", customer: "Julia", issue: "Account issue", status: "resolved" },
  { id: "111", customer: "Kevin", issue: "Delayed refund", status: "pending" },
  {
    id: "112",
    customer: "Liam",
    issue: "Technical issue on app",
    status: "escalated",
  },
  {
    id: "113",
    customer: "Mia",
    issue: "Rude customer service",
    status: "pending",
  },
  {
    id: "114",
    customer: "Nathan",
    issue: "Multiple charges",
    status: "resolved",
  },
  {
    id: "115",
    customer: "Olivia",
    issue: "Discount not applied",
    status: "pending",
  },
  {
    id: "116",
    customer: "Patrick",
    issue: "Broken item received",
    status: "escalated",
  },
  { id: "117", customer: "Quinn", issue: "Login issues", status: "resolved" },
  {
    id: "118",
    customer: "Rachel",
    issue: "Order duplicated",
    status: "pending",
  },
  {
    id: "119",
    customer: "Sam",
    issue: "Wrong address delivery",
    status: "resolved",
  },
  {
    id: "120",
    customer: "Tina",
    issue: "Item quality complaint",
    status: "pending",
  },
];
export const escalatedIssues = [
  {
    id: "201",
    customer: "Alice",
    issue: "Refund dispute",
    status: "escalated",
    priority: "high",
    escalatedBy: "John Doe",
  },
  {
    id: "202",
    customer: "Bob",
    issue: "Account locked",
    status: "escalated",
    priority: "medium",
    escalatedBy: "Jane Smith",
  },
  {
    id: "203",
    customer: "Charlie",
    issue: "Fraudulent transaction",
    status: "escalated",
    priority: "high",
    escalatedBy: "Michael Brown",
  },
  {
    id: "204",
    customer: "David",
    issue: "Repeated delivery failure",
    status: "escalated",
    priority: "medium",
    escalatedBy: "Emily Clark",
  },
  {
    id: "205",
    customer: "Emma",
    issue: "Product missing in package",
    status: "escalated",
    priority: "low",
    escalatedBy: "Robert Wilson",
  },
  {
    id: "206",
    customer: "Frank",
    issue: "Damaged product, no refund",
    status: "escalated",
    priority: "high",
    escalatedBy: "Sophia Anderson",
  },
  {
    id: "207",
    customer: "Grace",
    issue: "Order cancellation denied",
    status: "escalated",
    priority: "low",
    escalatedBy: "Daniel Martinez",
  },
  {
    id: "208",
    customer: "Hannah",
    issue: "Payment deducted twice",
    status: "escalated",
    priority: "high",
    escalatedBy: "Olivia Taylor",
  },
  {
    id: "209",
    customer: "Ian",
    issue: "Technical issue with app",
    status: "escalated",
    priority: "medium",
    escalatedBy: "Liam Harris",
  },
  {
    id: "210",
    customer: "Jack",
    issue: "Customer service unresponsive",
    status: "escalated",
    priority: "high",
    escalatedBy: "Mia Thompson",
  },
];

export const customerSatisfactionData = [
  {
    id: "1",
    customerName: "Alice",
    rating: 5,
    feedbackComment: "Great service!",
    satisfactionType: "Customer Satisfaction Score",
  },
  {
    id: "2",
    customerName: "Bob",
    rating: 8,
    feedbackComment: "Good experience.",
    satisfactionType: "Net Promoter Score",
  },
  {
    id: "3",
    customerName: "Charlie",
    rating: 3,
    feedbackComment: "Support took too long.",
    satisfactionType: "Customer Effort Score",
  },
  {
    id: "4",
    customerName: "David",
    rating: 7,
    feedbackComment: "Helpful support.",
    satisfactionType: "Net Promoter Score",
  },
  {
    id: "5",
    customerName: "Eve",
    rating: 2,
    feedbackComment: "Confusing process.",
    satisfactionType: "Customer Effort Score",
  },
];
export const responseTimes = [
  { id: "1", responseTime: 5 }, // 5 minutes
  { id: "2", responseTime: 12 }, // 12 minutes
  { id: "3", responseTime: 8 }, // 8 minutes
  { id: "4", responseTime: 15 }, // 15 minutes
  { id: "5", responseTime: 3 }, // 3 minutes
];
export const channels = [
  {
    id: "1",
    name: "Phone Support",
    status: "Active",
    lastActivity: "10 mins ago",
  },
  {
    id: "2",
    name: "Email Support",
    status: "Inactive",
    lastActivity: "1 hour ago",
  },
  { id: "3", name: "Live Chat", status: "Active", lastActivity: "5 mins ago" },
  { id: "4", name: "WhatsApp", status: "Active", lastActivity: "20 mins ago" },
  {
    id: "5",
    name: "Social Media",
    status: "Under Maintenance",
    lastActivity: "3 hours ago",
  },
];
